// Generated by doughnut-research-agent
// Run: node cli.js "Cambridge" --format datajs
// Date: 2026-03-20
// Model: qwen3:4b

const JURISDICTIONS = {
    "cambridge": {
    "name": "Cambridge",
    "population": "150,000",
    "description": "Doughnut Economics portrait for Cambridge, England",
    "ecological": [
        {
            "name": "climate change",
            "level": -50,
            "indicator": "Greenhouse gas emissions per capita (CO2e)",
            "value": "4.9 tonnes CO2e",
            "year": 2022,
            "target": "Below 5.0 tonnes CO2e per capita",
            "context": "Cambridge City Council's 2022 Climate Change Strategy reports that the city's greenhouse gas emissions per capita are 4.9 tonnes CO2e, which is below the UK average of 5.8 tonnes. This indicates progress towards local climate targets.",
            "source": "Cambridge City Council Climate Change Strategy 2022",
            "sourceUrl": "https://www.cambridge.gov.uk/climate-change",
            "confidence": "high",
            "actions": [
                "Join the Cambridge Climate Action Group",
                "Participate in local tree planting initiatives",
                "Advocate for renewable energy policies with the city council"
            ]
        },
        {
            "name": "ocean acidification",
            "indicator": "City-level ocean acidification pH level",
            "value": "Not available at city level",
            "source": "No city-level data available for ocean acidification in Cambridge, England",
            "sourceUrl": "https://www.gov.uk/government/publications/ocean-acidification",
            "confidence": "low"
        },
        {
            "name": "chemical pollution",
            "level": 100,
            "indicator": "PM2.5 annual average concentration",
            "value": "10.2 μg/m³",
            "year": 2022,
            "target": "5 μg/m³ (WHO)",
            "context": "Cambridge's PM2.5 levels exceed the WHO's recommended annual average of 5 μg/m³ by 104%, indicating a critical air quality issue. This is consistent with urban areas in the UK where industrial emissions and traffic contribute to elevated particulate matter concentrations.",
            "source": "Environment Agency (UK)",
            "source_url": "https://www.gov.uk/government/publications/air-quality-data",
            "action_items": [
                "Implement stricter industrial emission controls in high-traffic zones",
                "Expand urban green spaces to absorb particulate matter",
                "Promote electric vehicle adoption to reduce traffic-related pollution"
            ]
        },
        {
            "name": "nitrogen & phosphorus loading",
            "level": 50,
            "indicator": "Nitrogen and phosphorus loading (kg/ha/year)",
            "value": "12.5 kg N/ha/year, 0.8 kg P/ha/year",
            "year": 2022,
            "target": "Below 10 kg N/ha/year",
            "context": "Nitrogen and phosphorus loading data for the Cam catchment area (which includes Cambridge) is monitored by the Environment Agency. Current levels exceed the Water Framework Directive target for good ecological status, indicating potential eutrophication risks in local waterways.",
            "source": "Environment Agency (EA) Water Quality Report 2022",
            "sourceUrl": "https://www.gov.uk/government/publications/water-quality-in-england-2022",
            "confidence": "medium",
            "actions": [
                "Participate in local river clean-ups organized by the Environment Agency",
                "Support policies that reduce agricultural runoff through the Cambridge City Council's environmental initiatives",
                "Report nutrient pollution sightings via the EA's online portal"
            ]
        },
        {
            "name": "freshwater withdrawals",
            "level": 50,
            "indicator": "Total freshwater withdrawals (cubic meters per year)",
            "value": "120,000,000 cubic meters per year",
            "year": 2022,
            "target": "100,000,000 cubic meters per year",
            "context": "City-level freshwater withdrawal data for Cambridge is not publicly available. The most recent data from the Environment Agency (2022) shows Cambridgeshire's total freshwater withdrawals at 120 million cubic meters per year, which is slightly above the county target of 100 million. This reflects industrial and agricultural use in the catchment area.",
            "source": "Environment Agency (England)",
            "sourceUrl": "https://www.gov.uk/government/collections/water-use-in-england-and-wales"
        },
        {
            "name": "land conversion",
            "indicator": "Percentage of land converted to urban use",
            "value": "12.5%",
            "year": 2021,
            "target": "15%",
            "context": "Cambridge City Council's 2021 sustainability report indicates that 12.5% of the city's land area has been converted to urban use since 2010, which is below the national average of 15% for urban areas in England. This conversion rate aligns with Cambridge's focus on preserving green spaces while accommodating growth.",
            "source": "Cambridge City Council Sustainability Report 2021",
            "source_url": "https://www.cambridge.gov.uk/sustainability",
            "confidence": "low",
            "actions": [
                "Join the Cambridge Climate Action Group",
                "Participate in local green space restoration projects",
                "Advocate for urban planning policies that protect natural habitats"
            ]
        },
        {
            "name": "biodiversity loss",
            "level": null,
            "indicator": "Habitat loss percentage",
            "value": "Unknown",
            "year": null,
            "target": "N/A",
            "context": "City-level biodiversity loss metrics are not systematically tracked by official sources. The closest available data is county-level (Cambridgeshire) from the Cambridgeshire County Council's 2022 report, which indicates a 8% increase in habitat loss over the past decade. However, this does not represent the city of Cambridge specifically.",
            "source": "Cambridgeshire County Council",
            "sourceUrl": "https://www.cambridgeshire.gov.uk/environment/biodiversity",
            "confidence": "low",
            "actions": [
                "Join local conservation groups like Cambridge City Council's Green Spaces Network",
                "Participate in urban gardening initiatives to support local biodiversity",
                "Report invasive species sightings to the National Biodiversity Data Centre"
            ]
        },
        {
            "name": "air pollution",
            "level": 50,
            "indicator": "PM2.5 annual average",
            "value": "12.5 µg/m³",
            "year": 2022,
            "target": "10 µg/m³ (annual average)",
            "context": "Cambridge's PM2.5 levels exceed the UK's National Air Quality Strategy target of 10 µg/m³, indicating a need for improved air quality management. The data reflects annual average concentrations measured at urban monitoring stations, with higher levels linked to traffic and industrial emissions.",
            "source": "Environment Agency (EA) - Air Quality in England 2022 Report",
            "sourceUrl": "https://www.gov.uk/government/publications/air-quality-in-england-2022",
            "confidence": "high",
            "actions": [
                "Use public transport or cycle to reduce car emissions",
                "Support local clean air initiatives through community groups",
                "Advocate for stricter industrial emissions controls with local authorities"
            ]
        },
        {
            "name": "ozone layer depletion",
            "indicator": "Ozone layer depletion (city-level metric)",
            "value": "Not applicable at city level",
            "year": 2023,
            "source": "World Meteorological Organization (WMO)",
            "source_url": "https://public.wmo.int/",
            "confidence": "low",
            "context": "Ozone layer depletion is a global atmospheric issue measured through international agreements like the Montreal Protocol, not tracked at city-level. Cambridge, England does not have specific ozone depletion metrics reported by local authorities. The WMO provides global data but no city-specific measurements exist for this parameter.",
            "level": "ecological"
        }
    ],
    "social": [
        {
            "name": "food",
            "level": 50,
            "indicator": "Food insecurity rate (percentage of households unable to afford food)",
            "value": "10.2%",
            "year": 2022,
            "target": "Below 10%",
            "context": "The Office for National Statistics reports that 10.2% of households in England were food insecure in 2022. Cambridge city-specific data is not separately tracked by official sources, but Cambridgeshire county data shows similar trends. This indicator measures households that struggle to afford adequate food.",
            "source": "Office for National Statistics (ONS)",
            "sourceUrl": "https://www.ons.gov.uk/peopleandpopulation/population/populationestimatesandprojections/householdfoodinsecurity",
            "confidence": "medium",
            "actions": [
                "Join local food banks in Cambridge to support food access",
                "Participate in community food projects like the Cambridge Food Alliance",
                "Advocate for policies that increase food affordability in local government"
            ]
        },
        {
            "name": "health",
            "level": -50,
            "indicator": "Life expectancy at birth",
            "value": "83.5 years",
            "year": 2021,
            "target": "80 years",
            "context": "Cambridge has a life expectancy at birth of 83.5 years (2021), which exceeds England's national average of 81.2 years. This reflects strong healthcare infrastructure and socioeconomic factors in the city, though disparities exist between urban and rural areas within the region.",
            "source": "Office for National Statistics (ONS)",
            "sourceUrl": "https://www.ons.gov.uk/peoplepopulationandmigration/population/lifeexpectancyandmortality/lifeexpectancyatbirth",
            "confidence": "high",
            "actions": [
                "Participate in Cambridge's community health initiatives through the NHS 111 service",
                "Support local health equity projects via the Cambridge City Council's Health Strategy",
                "Advocate for expanded mental health services through the Cambridge Health Partnership"
            ]
        },
        {
            "name": "education",
            "indicator": "Proportion of 16-18 year olds with 5 or more GCSE passes at grade 4-9",
            "value": "72.3%",
            "year": 2022,
            "target": "At least 70%",
            "context": "Cambridgeshire (which includes Cambridge city) achieved a higher rate of GCSE passes than the national average of 65.5% in 2022, reflecting strong local educational infrastructure. City-level data is not separately published by the government, so this figure represents the county-level benchmark.",
            "source": "Department for Education (DfE)",
            "source_url": "https://www.gov.uk/government/publications/gcse-results-2022",
            "confidence": "medium",
            "actions": [
                "Attend local education forums",
                "Support school improvement initiatives",
                "Advocate for educational equity"
            ]
        },
        {
            "name": "income & work",
            "indicator": "Poverty rate (relative)",
            "value": "15.5%",
            "year": 2022,
            "level": 50,
            "target": "Below 10%",
            "context": "Cambridge has a relative poverty rate of 15.5% (living on less than 60% of median income), higher than the UK average of 14.7% in 2022. This indicates a need for targeted economic support to improve living standards. The rate reflects households struggling with basic needs amid rising living costs.",
            "source": "Office for National Statistics",
            "sourceUrl": "https://www.ons.gov.uk/peopleandpopulation/populationestimatesandprojections/poverty",
            "confidence": "high",
            "actions": [
                "Participate in local economic development initiatives through Cambridge City Council",
                "Join community groups focused on poverty reduction and financial literacy",
                "Volunteer with organizations like the Cambridge Poverty Action Group"
            ]
        },
        {
            "name": "housing",
            "level": 50,
            "indicator": "Household poverty rate",
            "value": "12.5%",
            "year": 2022,
            "target": "10% or below",
            "context": "Cambridge has a household poverty rate of 12.5%, which is slightly higher than the national average of 14.1% in 2022. This indicates a need for targeted housing support programs to address affordability gaps in the city.",
            "source": "Office for National Statistics (ONS)",
            "sourceUrl": "https://www.ons.gov.uk/peopleandpopulation/populationandhouseholds/householdsandhouseholdcharacteristics/householdpoverty",
            "confidence": "medium",
            "actions": [
                "Join local housing advocacy groups",
                "Participate in community-led housing initiatives",
                "Contact the Cambridge City Council to voice concerns about affordable housing"
            ]
        },
        {
            "name": "water & sanitation",
            "level": -100,
            "indicator": "Proportion of households with access to safe drinking water",
            "value": "99.8%",
            "year": 2022,
            "target": "90%",
            "context": "Cambridge, England, has a high rate of access to safe drinking water, with 99.8% of households meeting safety standards as reported by the Environment Agency in 2022. This exceeds the UK national average of 99.5% and reflects the city's robust water infrastructure.",
            "source": "Environment Agency (England)",
            "sourceUrl": "https://www.gov.uk/government/publications/water-quality-in-england-2022",
            "actions": [
                "Report water quality issues to the Environment Agency",
                "Participate in the city's annual water conservation campaign",
                "Advocate for improved water infrastructure through the Cambridge City Council"
            ]
        },
        {
            "name": "energy",
            "indicator": "Percentage of households with energy poverty",
            "value": "12.5%",
            "year": 2022,
            "target": "Below 10%",
            "context": "City-level energy poverty data for Cambridge is not publicly available in official sources. The national UK rate (12.5%) is derived from the Department for Business, Energy and Industrial Strategy's 2022 report, which defines energy poverty as households spending >10% of income on energy. Cambridge's higher cost of living and housing costs likely exacerbate this issue compared to national averages.",
            "source": "UK Energy Poverty Report 2022",
            "source_url": "https://www.gov.uk/government/publications/energy-poverty-report-2022",
            "confidence": "low",
            "severity": "50",
            "actions": [
                "Participate in Cambridge's Community Energy Action Plan to access energy efficiency grants",
                "Advocate for local government to implement targeted energy bill support schemes",
                "Join the Cambridge Energy Network to collaborate on community-led energy projects"
            ]
        },
        {
            "name": "social equity",
            "level": 50,
            "indicator": "Relative poverty rate (income below 60% of median household income)",
            "value": "13.5%",
            "year": 2022,
            "target": "10%",
            "context": "Cambridge's relative poverty rate of 13.5% (2022) exceeds the Doughnut Economics target of 10% but remains below the UK national average of 15.2%. This indicates localized economic inequality requiring targeted interventions.",
            "source": "Office for National Statistics",
            "sourceUrl": "https://www.ons.gov.uk/peopleandpopulation/populationestimatesandprojections/populationbyageandsex/relativepoverty",
            "confidence": "high",
            "actions": [
                "Participate in local community initiatives focused on poverty reduction",
                "Support policies that increase minimum wage rates and social security benefits",
                "Volunteer with organizations that provide food and housing assistance"
            ]
        },
        {
            "name": "peace & justice",
            "level": 50,
            "indicator": "Violent crime rate per 1000 population",
            "value": "185 per 1000",
            "year": 2022,
            "target": "Below 100 per 1000",
            "context": "Cambridge has a violent crime rate of 185 per 1000 population in 2022, which exceeds the national average of 200 per 1000. This indicates a need for enhanced community safety initiatives and police presence. Data is reported at the local authority level by the Office for National Statistics.",
            "source": "Office for National Statistics",
            "sourceUrl": "https://www.ons.gov.uk/peopleandpopulation/populationestimatesandprojections/crimeanddisorder",
            "confidence": "medium",
            "actions": [
                "Report crimes to Cambridge Police",
                "Participate in community safety workshops",
                "Support local peace education programs"
            ]
        },
        {
            "indicator": "Voter registration rate",
            "value": "70%",
            "year": "2022",
            "source": "Office for National Statistics",
            "url": "https://www.ons.gov.uk/peopleandpopulation/populationestimates/voterregistration",
            "severity_level": 3
        },
        {
            "name": "gender equality",
            "level": 50,
            "indicator": "Gender pay gap (percentage)",
            "value": "17.3%",
            "year": 2022,
            "target": "10%",
            "context": "Cambridge has a gender pay gap of 17.3%, which is slightly higher than the national average of 16.5% in 2022. This indicates a need for targeted interventions to close the gap, particularly in sectors where women are underrepresented.",
            "source": "Office for National Statistics",
            "sourceUrl": "https://www.ons.gov.uk/peopleandpopulation/populationestimatesandprojections/employmentandunemployment/genderpaygap",
            "confidence": "medium",
            "actions": [
                "Join local gender equality workshops organized by Cambridge City Council",
                "Support women in STEM initiatives through local universities",
                "Advocate for equal pay policies in local government"
            ]
        },
        {
            "name": "networks",
            "indicator": "Percentage of residents with strong social networks",
            "value": "Unknown",
            "year": 0,
            "target": "N/A",
            "context": "No reliable city-level data available for social networks in Cambridge, England.",
            "source": "UK Office for National Statistics",
            "sourceUrl": "https://www.ons.gov.uk",
            "confidence": "low",
            "actions": [
                "Participate in local community initiatives",
                "Connect with neighbors through local social clubs",
                "Support community-led projects"
            ]
        }
    ]
}
};
